### ISSUE TITLE
Complex number

### ISSUE THREAD

**Issue by YingboHuang** [jballard28/PDR#1]
Hi Jenna,

I heard of your talk last year ASHG and I am very interested in using PDR. However, I have faced with issues of complex number. After I running the DATA function on my own sumstats. the data object have complex number as showed in the following pics. 
![image](https://user-images.githubusercontent.com/78988040/160913282-36772980-d206-42f4-aac7-f33e8a5225b4.png)

Do you have any ideas how this problem come from? I have generated my sumstats from the ldsc munge_sumstats.py code and have all columns as required in PDR. 

Thanks in advance, 
Yingbo

**Comment by jballard28** [comment]
Hi Yingbo,

This is likely because the trait you are using is underpowered, so the sigmaEps value is too large, causing the covariance of alpha, as calculated within the normalize function in DATA, to be less than zero. I have added a check for whether this value is not positive and the function should now throw an error if this occurs.

Best,
Jenna
